version: '3.7'
networks:
  servarr:
	name: servarr
	external: true

services:
  recyclarr:
	image: ghcr.io/recyclarr/recyclarr
	container_name: recyclarr
	user: 1001:1001
	networks: [recyclarr]
	volumes:
	  - ./config:/config
	environment:
	  - TZ=America/New_York