version: '3.8'

networks:
  servarr:
    name: servarr
    driver: bridge

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1001:1001
    networks: [servarr]
    volumes:
      - /opt/recyclarr:/config
    environment:
      - TZ=America/New_York
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
  environment:
    - PUID=1001
    - PGID=1001
    - TZ=Americas/New_York
  volumes:
    - /opt/sonarr:/config
    - /media/naslib/plex/library:/tv #optional
    - /media/naslib/plex/sabnzbd/complete:/downloads #optional
  ports:
    - 8989:8989
  restart: unless-stopped