version: '3.8'

services:
  stash:
    image: hotio/stash
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
          max-file: "10"
          max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /etc/localtime:/etc/localtime:ro
     ## Keep configs, scrapers, and plugins here.
      - /opt/stash/.stash:/root/.stash
     ## Point this at your collection.
      - /media/adult:/data
     ## This is where your stash's metadata lives
      - /media/stashdb/metadata:/metadata
     ## Any other cache content.
      - /media/stashdb/cache:/cache
     ## Where to store binary blob data (scene covers, images)
      - /media/stashdb/blobs:/blobs
     ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /media/stashdb/generated:/generated
      - /media/stashdb/db:/database
  fileflows:
    image: revenz/fileflows
    container_name: fileflows
    runtime: nvidia
    environment:
      - PUID=1001
      - PGID=3000
      - TZ=America/New_York
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
      - FFNODE=1
      - NodeName=fileflows-plex2-node
      - ServerUrl=http://192.168.1.70:5000
      - TempPathHost=/tmp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/fileflows:/app/Data
      - /var/log/FileFlow:/app/Logs
      - /mnt/docker/fileflows/temp:/temp
      - /media/naslib/plex/library:/media
      - /media/adult/plex/library:/media2
      - /media/naslib/plex/sabnzbd:/downloads  #downloads
    ports:
      - 5000:5000
    restart: unless-stopped
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
