version: '3.8'

networks:
  servarr:
    name: servarr
    driver: bridge

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    user: 1001:1001
    networks: [servarr]
    volumes:
      - /opt/recyclarr:/config
    environment:
      - TZ=America/NewYork
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Americas/NewYork
    volumes:
      - /opt/sonarr:/config
      - /media/naslib/plex/library/Series:/tv #optional
      - /media/naslib/plex/sabnzbd/complete:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Americas/NewYork
    volumes:
      - /opt/radarr:/config
      - /media/naslib/plex/library/Movies:/movies #optional
      - /media/naslib/plex/sabnzbd/complete:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Americas/NewYork
    volumes:
      - /opt/sabnzbd:/config
      - /media/naslib/plex/sabnzbd/complete:/downloads #optional
      - /media/naslib/plex/sabnzbd/incomplete:/incomplete-downloads #optional
    ports:
      - 5678:8080
    restart: unless-stopped
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
          max-file: "10"
          max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
     ## Keep configs, scrapers, and plugins here.
      - /opt/stash/.stash:/root/.stash
     ## Point this at your collection.
      - /media/naslib:/data
     ## This is where your stash's metadata lives
      - /media/stashdb/metadata:/metadata
     ## Any other cache content.
      - /media/stashdb/cache:/cache
     ## Where to store binary blob data (scene covers, images)
      - /media/stashdb/blobs:/blobs
     ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /media/stashdb/generated:/generated
      - /media/stashdb/db:/database
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock