version: '3.8'

services:
  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    user: 1001:1001
      networks:
       - servarr
    volumes:
	  - ./config:/config
	  environment:
	  - TZ=America/New_York

networks:
	servarr:
		external: true
		name: servarr